const s = {
  page: { fontFamily: "var(--font-ui)", color: "var(--color-fg)", background: "var(--color-bg)", minHeight: "100vh" },

  // header
  header: { display: "grid", gridTemplateColumns: "1fr auto 1fr", alignItems: "center", padding: "14px 48px", borderBottom: "1px solid var(--color-grey-100)", background: "var(--color-white)" },
  wordmark: { fontFamily: "var(--font-display)", fontSize: 22, fontWeight: 300, letterSpacing: "0.06em", color: "var(--color-fg)" },
  headerCenter: { display: "flex", justifyContent: "center" },
  nav: { display: "flex", alignItems: "center", gap: 12, justifyContent: "flex-end" },
  // search
  searchWrap: { position: "relative", width: 320 },
  searchInput: { width: "100%", fontFamily: "var(--font-ui)", fontSize: 13, color: "var(--color-fg)", padding: "8px 16px", border: "1px solid var(--color-grey-100)", borderRadius: 20, outline: "none", background: "var(--color-bg)", boxSizing: "border-box" },
  searchDropdown: { position: "absolute", top: "calc(100% + 6px)", left: 0, right: 0, background: "var(--color-white)", border: "1px solid var(--color-grey-100)", borderRadius: 4, boxShadow: "0 8px 32px rgba(26,26,24,0.10)", zIndex: 200, overflow: "hidden" },
  searchResultItem: { display: "flex", alignItems: "center", gap: 12, padding: "10px 16px", cursor: "pointer", borderBottom: "1px solid var(--color-grey-100)" },
  searchResultAvatar: { width: 28, height: 28, borderRadius: "50%", background: "var(--color-fg)", color: "var(--color-bg)", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--font-display)", fontSize: 12, fontWeight: 300, flexShrink: 0 },
  navEmail: { fontFamily: "var(--font-ui)", fontSize: 12, color: "var(--color-fg-muted)" },
  coinBadge: { display: "inline-flex", alignItems: "center", background: "#F0F0EE", border: "1px solid var(--color-grey-100)", borderRadius: 3, padding: "5px 10px" },
  hamburger: { display: "flex", alignItems: "center", justifyContent: "center", background: "none", border: "none", cursor: "pointer", padding: "4px", color: "var(--color-fg)" },

  // buttons
  btnPrimary:    { display: "inline-flex", alignItems: "center", gap: 6, fontFamily: "var(--font-ui)", fontSize: 11, letterSpacing: "0.04em", fontWeight: 500, padding: "7px 18px", borderRadius: 3, border: "1px solid var(--color-fg)", background: "var(--color-fg)", color: "var(--color-bg)", cursor: "pointer", transition: "opacity var(--transition)" },
  btnSecondary:  { display: "inline-flex", alignItems: "center", gap: 6, fontFamily: "var(--font-ui)", fontSize: 11, letterSpacing: "0.04em", padding: "7px 18px", borderRadius: 3, border: "1px solid var(--color-fg)", background: "transparent", color: "var(--color-fg)", cursor: "pointer", transition: "opacity var(--transition)" },
  btnGhost:      { display: "inline-flex", alignItems: "center", gap: 6, fontFamily: "var(--font-ui)", fontSize: 11, letterSpacing: "0.04em", padding: "7px 14px", borderRadius: 3, border: "1px solid var(--color-grey-100)", background: "transparent", color: "var(--color-fg-secondary)", cursor: "pointer", transition: "opacity var(--transition)" },
  btnSave:       { display: "inline-flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--font-ui)", fontSize: 10, letterSpacing: "0.04em", padding: "4px 10px", borderRadius: 3, border: "1px solid var(--color-grey-100)", background: "transparent", color: "var(--color-fg-muted)", cursor: "pointer", transition: "opacity var(--transition)" },
  btnSaveActive: { display: "inline-flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--font-ui)", fontSize: 10, letterSpacing: "0.04em", padding: "4px 10px", borderRadius: 3, border: "1px solid var(--color-accent-light)", background: "var(--color-accent-subtle)", color: "var(--color-accent-dark)", cursor: "pointer", transition: "opacity var(--transition)" },

  // landing
  landingMain:   { display: "flex", flexDirection: "column", alignItems: "stretch", padding: "96px 0 80px", gap: 80 },
  hero:          { alignSelf: "center", textAlign: "center", maxWidth: 640, padding: "0 24px" },
  heroEyebrow:   { fontFamily: "var(--font-ui)", fontSize: 10, letterSpacing: "0.16em", textTransform: "uppercase", color: "var(--color-fg-muted)", marginBottom: 28 },
  heroTitle:     { fontFamily: "var(--font-display)", fontSize: "clamp(52px, 8vw, 96px)", fontWeight: 300, lineHeight: 1.05, letterSpacing: "-0.02em", color: "var(--color-fg)", marginBottom: 28 },
  heroAnd:       { fontStyle: "italic", color: "var(--color-accent)", fontWeight: 300 },
  heroSub:       { fontFamily: "var(--font-display)", fontSize: 17, fontWeight: 400, lineHeight: 1.65, color: "var(--color-fg-secondary)" },
  showcaseRule:  { borderTop: "1px solid var(--color-grey-100)", margin: "0 48px" },
  showcase:      { width: "100%", position: "relative" },
  showcaseLabel: { fontFamily: "var(--font-ui)", fontSize: 10, letterSpacing: "0.14em", textTransform: "uppercase", color: "var(--color-fg-muted)", margin: "0 0 20px 48px" },
  fadeLeft:      { position: "absolute", top: 28, left: 0, width: 80, bottom: 0, background: "linear-gradient(to right, var(--color-bg), transparent)", pointerEvents: "none" },
  fadeRight:     { position: "absolute", top: 28, right: 0, width: 80, bottom: 0, background: "linear-gradient(to left, var(--color-bg), transparent)", pointerEvents: "none" },
  sampleCard:    { flexShrink: 0, width: 220, background: "var(--color-white)", border: "1px solid var(--color-grey-100)", borderRadius: 3, padding: "24px", display: "flex", flexDirection: "column", gap: 10 },

  // marketplace
  marketLayout:  { display: "flex", minHeight: "calc(100vh - 57px)" },
  sidebar:       { width: 220, borderRight: "1px solid var(--color-grey-100)", padding: "32px 24px", background: "var(--color-white)", flexShrink: 0, display: "flex", flexDirection: "column", gap: 10 },
  sidebarSection: { fontFamily: "var(--font-ui)", fontSize: 10, fontWeight: 500, letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--color-fg-muted)", margin: "6px 0 4px" },
  sidebarRule:   { border: "none", borderTop: "1px solid var(--color-grey-100)", margin: "6px 0" },
  sidebarInput:  { width: "100%", fontFamily: "var(--font-ui)", fontSize: 12, color: "var(--color-fg)", padding: "7px 10px", border: "1px solid var(--color-grey-100)", borderRadius: 3, outline: "none", background: "var(--color-bg)", boxSizing: "border-box" },
  filterRow:     { display: "flex", alignItems: "center", gap: 8, cursor: "pointer" },
  marketMain:    { flex: 1, padding: "32px 40px" },
  marketLabel:   { fontFamily: "var(--font-ui)", fontSize: 10, letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--color-fg-muted)", marginBottom: 24 },
  grid:          { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))", gap: 16 },
  conceptCard:   { background: "var(--color-white)", border: "1px solid var(--color-grey-100)", borderRadius: 3, padding: "24px", display: "flex", flexDirection: "column", gap: 10, transition: "border-color var(--transition)", cursor: "default" },
  conceptTitle:  { fontFamily: "var(--font-display)", fontSize: 26, fontWeight: 300, color: "var(--color-fg)", lineHeight: 1.15, margin: 0 },
  conceptDesc:   { fontFamily: "var(--font-ui)", fontSize: 12, color: "var(--color-fg-muted)", lineHeight: 1.6, flex: 1, margin: 0 },
  conceptFooter: { display: "flex", flexDirection: "column", gap: 6, marginTop: 8 },
  errorMsg:      { fontFamily: "var(--font-ui)", fontSize: 12, color: "var(--color-error)", border: "1px solid #E8D0D0", background: "#FDF5F5", borderRadius: 3, padding: "8px 12px", marginBottom: 24 },
  cardError:     { fontFamily: "var(--font-ui)", fontSize: 11, color: "var(--color-error)", margin: 0 },

  // modal
  overlay:         { position: "fixed", inset: 0, background: "rgba(26,26,24,0.4)", backdropFilter: "blur(3px)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 100 },
  modal:           { background: "var(--color-white)", borderRadius: 4, padding: "40px 44px", width: 380, boxShadow: "var(--shadow-xl)", position: "relative" },
  detailModal:     { background: "var(--color-white)", borderRadius: 4, padding: "48px 52px", width: 560, maxWidth: "90vw", boxShadow: "var(--shadow-xl)", position: "relative" },
  modalClose:      { position: "absolute", top: 16, right: 16, background: "none", border: "none", cursor: "pointer", color: "var(--color-fg-muted)", display: "flex", padding: 4 },
  modalTitle:      { fontFamily: "var(--font-display)", fontSize: 26, fontWeight: 300, letterSpacing: "-0.01em", textAlign: "center", marginBottom: 28, color: "var(--color-fg)" },
  modalForm:       { display: "flex", flexDirection: "column", gap: 14 },
  fieldGroup:      { display: "flex", flexDirection: "column", gap: 5 },
  fieldLabel:      { fontFamily: "var(--font-ui)", fontSize: 10, letterSpacing: "0.08em", textTransform: "uppercase", color: "var(--color-fg-secondary)" },
  fieldInput:      { fontFamily: "var(--font-ui)", fontSize: 13, color: "var(--color-fg)", padding: "9px 12px", border: "1px solid var(--color-grey-100)", borderRadius: 3, outline: "none", background: "var(--color-white)", width: "100%" },
  modalError:      { fontFamily: "var(--font-ui)", fontSize: 11, color: "var(--color-error)", textAlign: "center" },
  modalSwitch:     { marginTop: 20, fontFamily: "var(--font-ui)", fontSize: 12, color: "var(--color-fg-muted)", textAlign: "center" },
  modalSwitchLink: { color: "var(--color-fg)", fontWeight: 500, cursor: "pointer", textDecoration: "underline" },

  // profile page
  profileWrap:        { background: "var(--color-bg)", minHeight: "calc(100vh - 57px)", padding: "48px 0 80px" },
  profileInner:       { maxWidth: 960, margin: "0 auto", padding: "0 48px" },
  profileBack:        { display: "inline-flex", alignItems: "center", gap: 6, fontFamily: "var(--font-ui)", fontSize: 11, letterSpacing: "0.04em", color: "var(--color-fg-muted)", background: "none", border: "none", cursor: "pointer", padding: "0 0 32px", transition: "color var(--transition)" },
  profileHero:        { display: "flex", alignItems: "center", gap: 24, marginBottom: 40 },
  avatarCircleLg:     { width: 72, height: 72, borderRadius: "50%", background: "var(--color-fg)", color: "var(--color-bg)", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--font-display)", fontSize: 28, fontWeight: 300, flexShrink: 0 },
  profileName:        { fontFamily: "var(--font-display)", fontSize: 32, fontWeight: 300, color: "var(--color-fg)", letterSpacing: "-0.01em", margin: 0 },
  profileStats:       { display: "flex", alignItems: "center", background: "var(--color-white)", border: "1px solid var(--color-grey-100)", borderRadius: 4, padding: "20px 32px", marginBottom: 40 },
  profileStatItem:    { flex: 1, textAlign: "center" },
  profileStatDivider: { width: 1, height: 40, background: "var(--color-grey-100)", flexShrink: 0 },
  profileStatNum:     { fontFamily: "var(--font-display)", fontSize: 24, fontWeight: 300, color: "var(--color-fg)", margin: "0 0 4px" },
  profileTabBar:      { display: "flex", gap: 0, borderBottom: "1px solid var(--color-grey-100)", marginBottom: 40 },
  profileTab:         { fontFamily: "var(--font-ui)", fontSize: 12, letterSpacing: "0.04em", color: "var(--color-fg-muted)", background: "none", border: "none", borderBottom: "2px solid transparent", padding: "10px 20px 10px 0", cursor: "pointer", display: "inline-flex", alignItems: "center", gap: 8, transition: "color var(--transition)" },
  profileTabActive:   { color: "var(--color-fg)", borderBottom: "2px solid var(--color-fg)" },
  profileTabBadge:    { fontFamily: "var(--font-mono)", fontSize: 10, color: "var(--color-fg-muted)", background: "var(--color-bg-subtle)", border: "1px solid var(--color-grey-100)", borderRadius: 10, padding: "1px 6px" },
  profileContent:     { paddingBottom: 40 },
  profileEmpty:       { fontFamily: "var(--font-ui)", fontSize: 13, color: "var(--color-fg-muted)", fontStyle: "italic", paddingTop: 8 },
  profileGrid:        { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))", gap: 16 },
  profileCard:        { background: "var(--color-white)", border: "1px solid var(--color-grey-100)", borderRadius: 3, padding: "24px", display: "flex", flexDirection: "column", gap: 10 },
  profileCardTitle:   { fontFamily: "var(--font-display)", fontSize: 26, fontWeight: 300, color: "var(--color-fg)", lineHeight: 1.15, margin: 0 },
  profileCardDesc:    { fontFamily: "var(--font-ui)", fontSize: 12, color: "var(--color-fg-muted)", lineHeight: 1.6, flex: 1, margin: 0 },
  profileCardFooter:  { display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 8 },
  secondaManoBadge:   { display: "inline-flex", alignItems: "center", gap: 4, fontFamily: "var(--font-mono)", fontSize: 9, letterSpacing: "0.08em", textTransform: "uppercase", color: "var(--color-fg-muted)" },
  statLabel:          { fontFamily: "var(--font-ui)", fontSize: 10, letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--color-fg-muted)", margin: 0 },
  userRow:            { display: "flex", alignItems: "center", gap: 14, padding: "14px 18px", background: "var(--color-white)", border: "1px solid var(--color-grey-100)", borderRadius: 3, cursor: "pointer", transition: "border-color var(--transition)" },
  userRowAvatar:      { width: 36, height: 36, borderRadius: "50%", background: "var(--color-fg)", color: "var(--color-bg)", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "var(--font-display)", fontSize: 16, fontWeight: 300, flexShrink: 0 },
  notifDot:           { position: "absolute", top: -3, right: -5, background: "#E85B5B", color: "#fff", fontFamily: "var(--font-ui)", fontSize: 9, fontWeight: 600, borderRadius: 10, padding: "1px 4px", minWidth: 14, textAlign: "center", lineHeight: "14px", pointerEvents: "none" },
  offerAcceptBtn:     { display: "flex", alignItems: "center", justifyContent: "center", width: 26, height: 26, borderRadius: 4, border: "1px solid #86EFAC", background: "#F0FDF4", color: "#16A34A", cursor: "pointer", flexShrink: 0 },
  offerRejectBtn:     { display: "flex", alignItems: "center", justifyContent: "center", width: 26, height: 26, borderRadius: 4, border: "1px solid #FCA5A5", background: "#FEF2F2", color: "#DC2626", cursor: "pointer", flexShrink: 0 },
};

export default s;
